/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val http4kVersion: String = "4.12.0.0"
val kotlinVersion: String = "1.5.30"
val junitVersion: String = "5.7.2"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
	id("org.jetbrains.kotlin.jvm") version "1.5.30"
    // kotlin("jvm") version "1.5.30"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
	implementation("com.google.guava:guava:30.1.1-jre")
    
    // Application dependancies
    implementation("org.http4k:http4k-core:${http4kVersion}")
    implementation("org.http4k:http4k-format-jackson:${http4kVersion}")
    implementation("org.http4k:http4k-security-oauth:${http4kVersion}")

    
    // Use the Kotlin test library.
    // testImplementation("org.jetbrains.kotlin:kotlin-test")
    // Use the Kotlin JUnit integration.
    // testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
    
	testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")

}

application {
    // Define the main class for the application.
    mainClass.set("tech.human.bptrk.AppKt")
}



// ==============================================================================

// We need to add this when we brought in the Http4K sample classes.

java.sourceCompatibility = JavaVersion.VERSION_1_8

val compileKotlin: KotlinCompile by tasks
val compileTestKotlin: KotlinCompile by tasks

compileKotlin.kotlinOptions {
	jvmTarget = "1.8"
}





/*
//tasks.withType(KotlinCompile) {
//    sourceCompatibility = JavaVersion.VERSION_1_8
//    targetCompatibility = JavaVersion.VERSION_1_8
//
//    kotlinOptions {
//        jvmTarget = '1.8'
//        apiVersion = '1.1'
//        languageVersion = '1.1'
//    }
//}
*/


//tasks.withType<KotlinCompile> {
//    kotlinOptions {
//        freeCompilerArgs = listOf("-Xjsr305=strict")
//        jvmTarget = "11"
//    }
//}

//tasks.withType<Test> {
//    useJUnitPlatform()
//}
